### ISSUE TITLE
Filter items formatting

### ISSUE THREAD

**Issue by hellodeborahuk** [the-collab-lab/tcl-44-smart-shopping-list#52]
1. I don't think we need the filter items label, or it needs to look different if it stays.
![filter items](https://user-images.githubusercontent.com/29425781/170116637-beefa910-e266-48b3-9949-533a795e6af0.png)

We could change the placeholder text to "Search items..." or "Filter items..."

2. The input size and position doesn´t match the figma design.  The input size of the list page will be different to the others. 
![input-size-issue](https://user-images.githubusercontent.com/84801660/170455976-563fa3bf-da01-4fd4-a520-630b05c75036.JPG)

**Comment by redapy** [comment]
you are right! this issue could also include adding the role to the unstyled list

**Comment by JimeBlue** [comment]
I haven´t @redapy . My issue was arranging the style of the home page not the list 😉

**Comment by JimeBlue** [comment]
Yes, totally agree with both commets.

**Comment by JimeBlue** [comment]
I think the placeholder saying "Search items" sounds better than "filter items"

**Comment by redapy** [comment]
I mixed the pages and the inputs because both don't need the label :). I edited my comment ;)

**Comment by JimeBlue** [comment]
I see now why I was confused. All good, too many inputs without label 😄
